### ISSUE TITLE
Cannot Recreate Example - no function clause matching in Mix.Tasks.Compile.Rustler.compile_crate/1    

### ISSUE THREAD

**Issue by cdesch** [rusterlium/NifIo#2]
I was trying to recreate the example [here](https://github.com/cdesch/rustler_test_project) and I keep running into this error ` no function clause matching in Mix.Tasks.Compile.Rustler.compile_crate` in the compile phase. Is this because I'm using elixir 1.5 or a specific version of rust (`rustc 1.21.0 (3b72af97e 2017-10-09)`)? 

```

cjs-MBP15:rustler_test_project cj$ iex -S mix
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

** (FunctionClauseError) no function clause matching in Mix.Tasks.Compile.Rustler.compile_crate/1    
    
    The following arguments were given to Mix.Tasks.Compile.Rustler.compile_crate/1:
    
        # 1
        "/native/mymodule"
    
    lib/mix/tasks/compile.rustler.ex:27: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
cjs-MBP15:rustler_test_project cj$ mix compile
** (FunctionClauseError) no function clause matching in Mix.Tasks.Compile.Rustler.compile_crate/1    
    
    The following arguments were given to Mix.Tasks.Compile.Rustler.compile_crate/1:
    
        # 1
        "/native/mymodule"
    
    lib/mix/tasks/compile.rustler.ex:27: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3

```

**Comment by cdesch** [comment]
It looks like the `rustler_crates` really needs to take in a private function like this:

```
  defp rustler_crates do
    [mymodule: [
      path: "native/mymodule",
      mode: (if Mix.env == :prod, do: :release, else: :debug),
    ]]
  end
```

It is referenced [here in the docs](https://hexdocs.pm/rustler/basics.html#crate-configuration)

The example may need to be updated. 

I was able to get [my example](https://github.com/cdesch/rustler_test_project) to run on Elixir 1.5 and Rust 1.21.0 just fine after some playing around.
